### ISSUE TITLE
Plugin doesn't show up on old versions of OctoPrint

### ISSUE THREAD

**Issue by rgelb** [derekantrican/OctoPrint-Webhooks#9]
I've installed the plugin, then rebooted the system.  

![image](https://github.com/derekantrican/OctoPrint-Webhooks/assets/1064250/2d440cf6-c3b3-41ab-8074-311e710ed4c5)

But I don't see any entry for OctoPrint-Webhooks under Plugins:

![image](https://github.com/derekantrican/OctoPrint-Webhooks/assets/1064250/a5ec72ae-a66b-4a36-93ff-1abb0211c829)

Here is my system information:

browser.user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0
connectivity.connection_check: 8.8.8.8:53
connectivity.connection_ok: true
connectivity.enabled: true
connectivity.online: true
connectivity.resolution_check: octoprint.org
connectivity.resolution_ok: true
env.hardware.cores: 4
env.hardware.freq: 900
env.hardware.ram: 917020672
env.os.bits: 32
env.os.id: linux
env.os.platform: linux2
env.plugins.pi_support.model: Raspberry Pi 2 Model B Rev 1.1
env.plugins.pi_support.octopi_version: 0.15.1
env.plugins.pi_support.throttle_state: 0x0
env.python.pip: 20.3.4
env.python.version: 2.7.13
env.python.virtualenv: true
octoprint.safe_mode: false
octoprint.version: 1.5.3

I am also just as happy to set it from the command line and place a file with necessary webhooks wherever, if you can tell me where to do it.

**Comment by derekantrican** [comment]
Looks like the plugin may have failed to load? Can you provide your octoprint.log file?

**Comment by rgelb** [comment]
Don't see anything in the file.  Here is the [relevant portion ](https://pastebin.com/Huf2eKsU)of it.

**Comment by derekantrican** [comment]
When restarting octoprint, I have this block at the beginning of the logs:
```
2023-06-30 15:49:53,804 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2023-06-30 15:49:53,811 - octoprint.server - INFO - --- Log roll over detected ---------------------------------------------------
2023-06-30 15:49:53,811 - octoprint.server - INFO - OctoPrint 1.9.0
2023-06-30 15:49:53,815 - octoprint.plugin.core - INFO - 36 plugin(s) registered with the system:
|  Action Command Notification Support (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/action_command_notification
|  Action Command Prompt Support (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/announcements
|  Anonymous Usage Tracking (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/tracking
|  Application Keys Plugin (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/appkeys
|  Backup & Restore (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/backup
|  Bed Visualizer (1.1.1) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_bedlevelvisualizer
|  Classic Webcam (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/classicwebcam
|  Convert TF to SD (1.0.2) = /home/pi/.octoprint/plugins/convert_TF_SD.py
|  Core Wizard (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/corewizard
|  Cura Thumbnails (1.0.2) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_ultimakerformatpackage
|  Dashboard (1.19.9) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_dashboard
|  Discovery (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/discovery
|  Error Tracking (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/errortracking
|  Event Manager (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/eventmanager
|  Exclude Region (0.3.2) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_excluderegion
|  Filament Sensor Simplified (0.3.3) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_filamentsensorsimplified
|  File Check (2021.2.23) (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_file_check
|  Firmware Check (2021.10.11) (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_firmware_check
|  Firmware Updater (1.14.0) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_firmwareupdater
|  GCode Viewer (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/gcodeviewer
|  Google Drive Backup (0.1.1) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_googledrivebackup
|  KasaCloud Plugin (0.1.0) = /home/pi/OctoPrint-KasaCloud/octoprint_KasaCloud
|  Logging (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/logging
|  Ngrok Tunnel (0.4.0) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_ngrok
|  OctoApp (1.2.3) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_octoapp
|  OctoPrint-IFTTT (1.4.1) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_IFTTT
|  Pi Support Plugin (2023.5.24) (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_pi_support
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/pluginmanager
|  PrintTimeGenius Plugin (2.3.0) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_PrintTimeGenius
|  Software Update (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/softwareupdate
|  Themeify (1.2.2) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_themeify
|  TP-Link Smartplug (1.0.3) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_tplinksmartplug
|  Virtual Printer (bundled) = /home/pi/oprint/lib/python3.7/site-packages/octoprint/plugins/virtual_printer
|  WebcamStreamer Plugin (0.1.1) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_webcamstreamer
|  Webhooks (4.1.0) = /home/pi/oprint/lib/python3.7/site-packages/octoprint_webhooks
Prefix legend: ! = disabled, # = blacklisted, * = incompatible
```

Can you share that portion?

**Comment by rgelb** [comment]
@derekantrican sure this.  It seems like its loading.  

```
2023-06-30 18:34:44,645 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2023-06-30 18:34:44,678 - octoprint.server - INFO - --- Log roll over detected ---------------------------------------------------
2023-06-30 18:34:44,679 - octoprint.server - INFO - OctoPrint 1.5.3
2023-06-30 18:34:44,688 - octoprint.plugin.core - INFO - 22 plugin(s) registered with the system:
|  Action Command Notification Support (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/action_command_notification
|  Action Command Prompt Support (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/announcements
|  Anonymous Usage Tracking (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/tracking
|  Application Keys Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/appkeys
|  Arc-Welder (1.0.0+u.bb71e8f) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_arc_welder
|  Backup & Restore (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/backup
|  Core Wizard (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/corewizard
|  Discovery (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/discovery
|  Error Tracking (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/errortracking
|  File Check (2021.2.23) (bundled) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_file_check
|  Firmware Check (2021.10.11) (bundled) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_firmware_check
|  GCode Viewer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/gcodeviewer
|  Lifx Switch (0.4.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_lifxswitch
|  Logging (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/logging
|  Malyan/Monoprice Connection Fix (0.1.3) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_malyan_connection_fix
|  Octolapse (0.4.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_octolapse
|  OctoPrint-Webhooks (4.1.0) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_webhooks
|  Pi Support Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/pi_support
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  Software Update (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  Virtual Printer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
Prefix legend: ! = disabled, # = blacklisted, * = incompatible
2023-06-30 18:34:44,721 - octoprint.environment - INFO - Detected environment is Python 2.7.13 under Linux (linux2). Details:
|  hardware:
|      cores: 4
|      freq: 900.0
|      ram: 917020672
|  os:
|      bits: 32
|      id: linux
|      platform: linux2
|  plugins:
|      pi_support:
|          model: Raspberry Pi 2 Model B Rev 1.1
|          octopi_version: 0.15.1
|          throttle_state: '0x0'
|  python:
|      pip: 20.3.4
|      version: 2.7.13
|      virtualenv: /home/pi/oprint
2023-06-30 18:34:44,722 - octoprint.server - INFO - ------------------------------------------------------------------------------
2023-06-30 18:34:45,105 - octoprint.plugins.discovery - INFO - Registered 'OctoPrint instance on octopi._octoprint._tcp.local.' for _octoprint._tcp.local.
2023-06-30 18:34:45,143 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on octopi for SSDP
2023-06-30 18:34:45,184 - octoprint.server - INFO - Listening on http://127.0.0.1:5000
2023-06-30 18:34:46,663 - octoprint.plugins.announcements - INFO - Loaded channel _important from https://octoprint.org/feeds/important.xml in 1.5s
2023-06-30 18:34:47,944 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from https://plugins.octoprint.org/plugins.json
2023-06-30 18:34:48,235 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2023-06-30 18:34:48,238 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2023-06-30 18:34:48,240 - octoprint.util.pip - INFO - ==> pip ok -> yes
2023-06-30 18:34:48,362 - octoprint.plugins.softwareupdate - INFO - Minimum free storage across all update relevant locations is 24.9GB. That is considered sufficient for updating.
2023-06-30 18:34:48,367 - octoprint.plugins.softwareupdate - INFO - Fetching check overlays from https://plugins.octoprint.org/update_check_overlay.json
2023-06-30 18:34:56,105 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2023-06-30 18:34:56,108 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2023-06-30 18:34:56,112 - octoprint.util.pip - INFO - ==> pip ok -> yes
2023-06-30 18:34:56,118 - octoprint.plugins.softwareupdate - ERROR - Could not check arc_welder for updates
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/__init__.py", line 1496, in _get_current_version
    target, check, online=online, credentials=credentials
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 305, in get_latest
    target
ConfigurationInvalid: Update configuration for arc_welder of type github_release needs all of user, repo and current set and not None
2023-06-30 18:34:56,723 - octoprint.plugins.pluginmanager - INFO - Loaded plugin notices data from https://plugins.octoprint.org/notices.json
2023-06-30 18:34:57,477 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2023-06-30 18:34:57,533 - octoprint.plugins.lifxswitch - INFO - Hello LifX World!
2023-06-30 18:34:57,534 - octoprint.plugins.lifxswitch - INFO - Getting settings...
2023-06-30 18:34:57,541 - octoprint.plugins.lifxswitch - INFO - access_token! (more: cb33939f22003eff664a056d523819fefaa30b448684e4ee0c090371afaff74d)
2023-06-30 18:34:57,545 - octoprint.plugins.lifxswitch - INFO - light_id! (more: 02478703-05b1-4d2c-8f2e-4976fda55dcb)
2023-06-30 18:34:58,058 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://192.168.1.2/'}
2023-06-30 18:34:59,359 - octoprint.plugins.tracking - INFO - Sent tracking event ping, payload: {'octoprint_uptime': 38}
2023-06-30 18:35:01,339 - octoprint.plugins.tracking - INFO - Sent tracking event startup, payload: {u'python': '2.7.13', u'os': u'linux', u'ram': 917020672, u'octopi_version': u'0.15.1', u'version': u'1.5.3', u'pip': '20.3.4', u'cores'$
2023-06-30 18:35:03,765 - octoprint.plugins.tracking - INFO - Sent tracking event pong, payload: {u'python': '2.7.13', u'os': u'linux', u'ram': 917020672, u'octopi_version': u'0.15.1', u'version': u'1.5.3', u'plugins': u'lifxswitch:0.4.$
2023-06-30 18:35:28,077 - octoprint.server.preemptive_cache - INFO - ... done in 30.02s


```

**Comment by derekantrican** [comment]
Sorry for the delay. Does seem like it's loading - maybe it's the python 2.7 difference? I'll have to test that on a spare pi. Is there a reason you're still on the "python 2.7 version" of octoprint? [This blog post](https://octoprint.org/blog/2020/09/10/upgrade-to-py3/) seems to indicate that octoprint will be only python 3 going forward.

Funny enough - I noticed the screenshot you shared at the top of this thread seems to indicate that the plugin isn't compatible with python 3. I'll have to see if I can update that.

**Comment by derekantrican** [comment]
@rgelb can you share what version of octopi & octoprint you are running? Better yet, do you mind providing a SystemInfo Bundle? https://community.octoprint.org/t/what-is-a-systeminfo-bundle-and-how-can-i-obtain-one/29887

**Comment by rgelb** [comment]
@derekantrican You are right, versions of octopi and octoprint are quite old.  0.15 and 1.5.3 respectively.  And its running under Python 2.7.  The reasons that I haven't upgraded are 

- the setup has been working fine for past X years and I'd rather not mess with it.  
- there is no software path to actually upgrade.  I [tried](https://community.octoprint.org/t/unable-to-upgrade-octoprint/52563), believe me.  Instead, you have to start from scratch.  But the problem is that over the years, I've made far too many tweaks in a million config files that I no longer remember.  Plus my setup is running on Raspberry Pi 2 which is no longer recommended.  And there was a period of time where I avoided upgrading like the plague (because of upgrade PTSD), so i missed that boat.
- the reason for wanting to install WebHooks is to send myself a text when the print is done.  A huge convenience, for sure, but not compared to building a new setup from scratch. 

That said, the systeminfo bundle is as follows

> browser.user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/114.0
> connectivity.connection_check: 8.8.8.8:53
> connectivity.connection_ok: true
> connectivity.enabled: true
> connectivity.online: true
> connectivity.resolution_check: [octoprint.org](http://octoprint.org/)
> connectivity.resolution_ok: true
> env.hardware.cores: 4
> env.hardware.freq: 900
> env.hardware.ram: 917020672
> env.os.bits: 32
> env.os.id: linux
> env.os.platform: linux2
> env.plugins.pi_support.model: Raspberry Pi 2 Model B Rev 1.1
> env.plugins.pi_support.octopi_version: 0.15.1
> env.plugins.pi_support.throttle_state: 0x0
> env.python.pip: 20.3.4
> env.python.version: 2.7.13
> env.python.virtualenv: true
> octoprint.safe_mode: false
> octoprint.version: 1.5.3
> printer.firmware: Malyan 3.5

**Comment by derekantrican** [comment]
Looks like this version is old enough that I can't even test it (doesn't seem to be compatible with raspberry pi 4). Do you mind sending me your entire octoprint.log file? You can send to derekantrican@gmail.com

**Comment by derekantrican** [comment]
Going to close as "Won't Fix" for now - but still feel free to send me the above info if you get a chance

**Comment by rgelb** [comment]
@derekantrican I did send the info to you on July 10th.  Perhaps it went to junk.  I am attaching the logs here.  
[octologs.zip](https://github.com/derekantrican/OctoPrint-Webhooks/files/12330821/octologs.zip)

**Comment by derekantrican** [comment]
@rgelb Oh, sorry about that! It must've. Thanks for copying it here
